### ISSUE TITLE
Host openmobility.eclipse.org on EF openshift infrastructure

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openmobility.eclipse.org#14]
As a temporary solution, we are currently hosting the site on our forge-vms but that won't scale.

We should deploy this new website on our openshift cluster once @mbarbero is back from vacation!

**Comment by mbarbero** [comment]
I've committed Jenkinsfile for CI/CD of this website (https://github.com/EclipseFdn/openmobility.eclipse.org/blob/master/Jenkinsfile). Whenever a push is made to master branch or staging branch (does not exist yet), a build is triggered on our internal Jenkins instance. The build starts a multi stage docker build (https://github.com/EclipseFdn/openmobility.eclipse.org/blob/master/Dockerfile) which creates a docker image that is pushed to docker hub.

Once the image is pushed to docker hub, the update is rolled out in the appropriate environment (production or staging). 

Currently, no notification on failed/successful build is send. What do we want to do? We can send email, slack notification etc...

The production and staging environment are described in https://github.com/EclipseFdn/openmobility.eclipse.org/tree/master/k8s.

**Comment by RobertHilbrich** [comment]
@mbarbero: thanks for setting it up. Notification via mail to sumo@dlr.de would be fine for the moment, since we do not have any openmobility-dev@eclipse.org mailing list yet.

**Comment by mbarbero** [comment]
The webdev team is notified on slack + email on failing build. Closing.
