### ISSUE TITLE
Image optimization

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/openmobility.eclipse.org#15]
Hi @angelobanse,

The @eclipsewebmaster noticed that images/logo/sumo.ico is 364 kb this morning.

https://github.com/EclipseFdn/openmobility.eclipse.org/blob/master/static/images/logo/sumo.ico

Would it be possible to make sure that the images are optimized for the web?

**Comment by angelobanse** [comment]
Ok, i will change that image to an PNG.
That image is used in https://openmobility.eclipse.org/news/community-news/ and not as a favicon.
