### ISSUE TITLE
Twitter block is not showing on IE11 but showing a link to twitter page

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/openmobility.eclipse.org#31]
**Describe the bug**
Twitter block is not showing on IE11 but showing a link to twitter page, and if clicking on the link Windows will automatically takes you to use Edge open the twitter.

**Screenshots**
![image](https://user-images.githubusercontent.com/39588094/93771304-5464cd00-fbeb-11ea-8e71-f9fc910214ed.png)
![image](https://user-images.githubusercontent.com/39588094/93771334-5e86cb80-fbeb-11ea-8c04-93d0bf6bcf7d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] WIN10
 - Browser [e.g. chrome, safari] IE11

**Comment by angelobanse** [comment]
The embedded timeline depends entirely on Twitter and their supported browsers. There isn't much we can do about it.
