### ISSUE TITLE
Remove travis build

### ISSUE THREAD

**Issue by mbarbero** [EclipseFdn/openmobility.eclipse.org#39]
I don't think travisci build is still used / useful. We should get rid of it. 

@chrisguindon WDYT?

**Comment by chrisguindon** [comment]
+1 as long as the community has access to public logs on jenkins!

**Comment by mbarbero** [comment]
Yep, community now has public access via https://foundation.eclipse.org/ci/webdev/job/public/

**Comment by mbarbero** [comment]
there has been no change for that.

**Comment by ericpoirier** [comment]
I removed Travis CI this week from this repo.
